### ISSUE TITLE
License of JEmpatheticDialogues and JPersonaChat datasets

### ISSUE THREAD

**Issue by ukky17** [nttcslab/japanese-dialog-transformers#8]
Thank you for the wonderful repository. I have a question about the license for the `JEmpatheticDialogues` and `JPersonaChat` datasets. 

The `README.md` contains the [regulations of using the models provided in the repository](https://github.com/nttcslab/japanese-dialog-transformers?tab=readme-ov-file#notice-for-using-the-codes). However, I am unsure about the license for the `JEmpatheticDialogues` and `JPersonaChat` datasets. Should I follow the `LICENSE.md` [provided in the repository](https://github.com/nttcslab/japanese-dialog-transformers/blob/main/LICENSE.md) for these datasets?

Thank you in advance.

**Comment by h-sugi** [comment]
Thank you for your kind words and for your interest in our repository. We appreciate your support and engagement.

Regarding your question about the license for the JEmpatheticDialogues and JPersonaChat datasets, please follow the LICENSE.md provided in the repository for these datasets. 

If you have any further questions, please don't hesitate to ask.

**Comment by ukky17** [comment]
Thank you for the quick reply!

**Comment by ukky17** [comment]
@h-sugi 

Based on the `Notice.md`, I am a bit confused because it mentions different restrictions for the dialogue data (which I assume refers to JEmpatheticDialogues and JPersonaChat datasets) than those in `LICENSE.md`. It mentions that the usage of the dialogue data must be limited to the evaluation purpose.

To get straight to the point, are the JEmpatheticDialogues and JPersonaChat datasets allowed to be used in a commercial dialogue service that is not limited to evaluation use?

**Comment by h-sugi** [comment]
We apologize for the confusion caused by the discrepancies between the Notice.md and LICENSE.md documents.

The use of this data is limited to evaluation purposes only, regardless of whether the institution is for-profit or non-profit. This includes training dialogue models with this data and verifying their performance through dialogue experiments with a limited number of subjects. However, using this data to build models for dialogue services is not permitted, whether for-profit or non-profit.

Does this answer your question?

**Comment by ukky17** [comment]
Thank you for the reply. I understand that the use of this data is limited to evaluation purposes.
